### PR TITLE
Add regular expressions and ranges

### PR DESCRIPTION
**Pull request by otacke**
I implemented regular expressions and ranges as answers without changing the current identifiers. The code might need a little more love, but please just have a look if you could possibly use it in general.

### CODE REVIEW

**Comment by timothyylim** [comment]
Great work otacke! I've made an issue for it to be merged:

https://h5ptechnology.atlassian.net/browse/HFP-321

**Comment by thomasmars** [comment]
Could you explain a bit more in detail what this pull request does and why it is needed ?

**Comment by timothyylim** [comment]
@thomasmars , I should have added a cross reference to the original feature request in the forums:

https://h5p.org/node/4402

**Comment by otacke** [comment]
In _Fill in the Blanks_, you have to give all valid answers explicitly. That may be a little extensive for multiple discrete numerical values, but possible. However, you might want to allow answers such as 50 +/- 0.5 (or a continuous range from 49.5 to 50.5). With my changes, you now could define this range as ((49.5,50.5)).

That was the easy part. I didn't stop there, but also implemented support for regular expressions by putting them between [[[ and ]]].

The best way would probably have been to write a parser, but for now I just modified the code.

You will find a demo at http://www.olivertacke.de/2016/12/03/just-some-fiddling-with-h5p/

**Comment by thomasmars** [comment]
Thanks :)

**Comment by falcon-git** [comment]
@otacke it is very impressive work. Do you think this will be used often? How would authors typically use this?

**Comment by otacke** [comment]
The ranges? Frequently. It was actually suggested by one of my colleagues.
The regular expressions? Probably rarely :-) I found the request in the forum and thought: "Well, I'm going to touch those lines of code anyway ..." ;-)

**Comment by otacke** [comment]
@falcon-git Oh, I didn't write anything about the use case. Sorry. There might be some use for ranges in math scenarios or just for estimating values instead of requiring exact solutions. For example, [Capira-Socrates](http://capira-solutions.com) is capable of using ranges ...

... and even mathematical equivalency which would be great to have for math questions.

**Comment by otacke** [comment]
Let me know of I should just close this one, please.

**Comment by anjalorenz** [comment]
Would be great if this could be supported. Just wanted to let users guess how much inhabitants we have here in Lübeck, thus a range of numbers would be very helpful.

**Comment by otacke** [comment]
Giving up on this one.

**Comment by chilbes** [comment]
Hi! I'm new to H5P. Sorry to find out your implementation got not enough attention. Checking whether a number is within a range would  be extremely useful for quizzes in all quantitative sciences (physics, chemistry, engineering, but also e. g. economics, medicine, etc) and math. No other requests for such a kind of feature? Or has it been implemented elsewhere? Any help is highly welcome!

**Comment by otacke** [comment]
@chilbes I don't think there's anything like this in H5P. No. Sorry.

**Pull request closed without merging**
